### ISSUE TITLE
Problems with expressions (likely just a problem with `NOT`)

### ISSUE THREAD

**Issue by Coding-Cactus** [dsoon/PS2#3]
There are some problems with nested expressions (or just `NOT` expressions).

- `NOT FALSE OR TRUE` => FALSE (should be TRUE)
- `NOT TRUE AND NOT TRUE` => TRUE (should be FALSE)
- `(NOT TRUE) AND (NOT TRUE)` => error:
```
Traceback (most recent call last):
  File "C:/Users/.../PS2/main.py", line 5, in <module>
    PS2.runPrompt()
  File "C:\Users\...\PS2\ps2\app.py", line 51, in runPrompt
    PS2.run("".join(prog))
  File "C:\Users\...\PS2\ps2\app.py", line 86, in run
    Interpretor(statements).interpret()
  File "C:\Users\...\PS2\ps2\interpret\interpretor.py", line 15, in interpret
    stmt.interpret()
  File "C:\Users\...\PS2\ps2\statement\statement.py", line 203, in interpret
    value = expr.evaluate()
  File "C:\Users\...\PS2\ps2\expr\expression.py", line 40, in evaluate
    left_value   = self.left.evaluate()
  File "C:\Users\...\PS2\ps2\expr\expression.py", line 142, in evaluate
    return self.visitNode(self.expression)
AttributeError: 'GROUPING' object has no attribute 'visitNode'
```

Problems appear to arise with the `NOT` appearing before an expression and then being handled as if it were `NOT (rest of expression)` rather than `(NOT next_item) ...`

**Comment by dsoon** [comment]
This has been fixed in the latest release.

1> PRINT FALSE OR TRUE
2> .
TRUE
1> PRINT NOT TRUE AND NOT FALSE
2> .
FALSE

Will review PRINT (NOT TRUE) AND  (NOT TRUE)


________________________________
From: Coding Cactus ***@***.***>
Sent: Monday, March 14, 2022 5:45:17 PM
To: dsoon/PS2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dsoon/PS2] Problems with expressions (Issue #3)


There are some problems with nested expressions.

  *   NOT FALSE OR TRUE => FALSE (should be TRUE)
  *   NOT TRUE AND NOT TRUE => TRUE (should be FALSE)
  *   (NOT TRUE) AND (NOT TRUE) => error:

Traceback (most recent call last):

  File "C:/Users/.../PS2/main.py", line 5, in <module>

    PS2.runPrompt()

  File "C:\Users\...\PS2\ps2\app.py", line 51, in runPrompt

    PS2.run("".join(prog))

  File "C:\Users\...\PS2\ps2\app.py", line 86, in run

    Interpretor(statements).interpret()

  File "C:\Users\...\PS2\ps2\interpret\interpretor.py", line 15, in interpret

    stmt.interpret()

  File "C:\Users\...\PS2\ps2\statement\statement.py", line 203, in interpret

    value = expr.evaluate()

  File "C:\Users\...\PS2\ps2\expr\expression.py", line 40, in evaluate

    left_value   = self.left.evaluate()

  File "C:\Users\...\PS2\ps2\expr\expression.py", line 142, in evaluate

    return self.visitNode(self.expression)

AttributeError: 'GROUPING' object has no attribute 'visitNode'

Problems appear to arise with the NOT appearing before an expression and then being handled as if it were NOT (rest of expression) rather than (NOT next_item) ...

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsoon%2FPS2%2Fissues%2F3&data=04%7C01%7C%7C3f7c1e4e1b214e241f8e08da05e267bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828767194841323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8%2FR9lyftKEGzZci3sIdwE2G0yqYs8k5OtdKrOKvNaUg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEXRFBV3WQN6FCODBDPXHBTU753K3ANCNFSM5QWISX7A&data=04%7C01%7C%7C3f7c1e4e1b214e241f8e08da05e267bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828767194841323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mqKmkCsqvhR5I4WrMAxQa%2B%2BSLk9Xjt36Hg%2BSsQRJCvM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C3f7c1e4e1b214e241f8e08da05e267bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828767194997558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zp9%2BLMs3Li6WkxKGoyFHh25CD85bGiJitBz2zE2YT7U%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C3f7c1e4e1b214e241f8e08da05e267bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828767194997558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JdzOujPt%2FWJwRmUUsOmVdEcHrAoxz2iZWKPME4mAg64%3D&reserved=0>.

**Comment by Coding-Cactus** [comment]
I am on an up to date fork of this repo and those cases I listed above are certainly not working. A possible reason for the `NOT TRUE AND NOT FALSE` example you just provided working could be because it is has the same result as `NOT (TRUE AND NOT FALSE)` which is what I am suggesting is being interpreted.

**Comment by dsoon** [comment]
Just committed a fix. Do you want to try it now.

**Comment by Coding-Cactus** [comment]
The statements with the brackets does now work. However, the other 2 statements still do not work.

![image](https://user-images.githubusercontent.com/65423356/158243707-7a6c7c0e-6d2d-4549-bd19-bff19006bc33.png)
Those 2 statements in the above image should return the same result, however, as you can see, they are different. The `NOT TRUE AND NOT TRUE` is incorrect.

Same with the other example statement provided earlier:
![image](https://user-images.githubusercontent.com/65423356/158243588-15300fdc-77d2-4617-a60a-8ad3a4deef70.png)

**Comment by dsoon** [comment]
Issue fixed.
![image](https://user-images.githubusercontent.com/19862150/158251755-37cd06d0-6676-40a1-a824-cc2a04ac7e8a.png)
